// date localization for locale 'ja', 'ja_jp', 'jp'
// generated by Jörn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['日', '月', '火', '水', '木', '金', '土'];
Date.abbrDayNames = ['日', '月', '火', '水', '木', '金', '土'];
Date.monthNames = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"];
Date.abbrMonthNames = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"];
